language: node_js
node_js: node
before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
  - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: L2/fU5sUQA+7A82syx+KHcZW1z/lULBzHFop6haX94Ne/YHRmdfxYYSPoC2aGekLVKvslizjGI9QaB/w3k02zjRKyrl7bf9QijFWktyzvI1r3RtQCKQN964ufgyXf7UZifwYa97i7Ieef7n2KpUzLtC9qxQ1oVMGyiW6IIhoWXUMgz67hZXCTPYlqYti4zK1UbicPDTgyoIB6AS5iZsbBCHqgN2qLl2iwMxhkrRyQ1rtyowlm964oTGMaiMAk3T3iC7q1zBCkKMfrqtTwwk54eMyK35DQOx7jkoI3KEA8nzKE+jMXy+R+EJlSEwGdixF9SzbQ1OPg9pc0oh3Q5I1B5C9+DPEigwnHY6+J7jtkgVub8b0QG9vq1vLyVDKC0O/5qoi/YquipNgY/iCRKm6NoEBpaYmiJp6imzCKAIwK8zmu2rUB8n2FWeWVp/DvCwK32/5hiAAI1v1cH8Kq9TMYmLyCsAVRd7EByi2QzcyoDwiYYYisl+14wVgpyrN9odGbA6siBUwV5sqY8B1t7un1v0jDN5cI02mjlu0/DtueHzeta3HCecv/yGcgLydRWLXCythK8NA/7OC6RvDjBxglJj5OH8fw1ejbUBZ2fXsSkrh1BenMvBPliUU5UVr4otwpA7AjDxtB00C+VE+LJdLF/uSM+dHxojJiDZhkaxcyB0=
  app: foodtracker-api
  on:
    repo: MattLong87/foodtracker-api
